apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-ncxo
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-ncxo
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-ncxo
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-ncxo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-ncxo
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-cdhx-tenant/rhtap-demo-app/hacbs-test-project-ncxo@sha256:4f0f49af4ff1bd42b4f6d6cec6e6baf20ef727a9fabf6b89544c4ee3a247ae37
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
